# HALF_WINDOW = 500
# WINDOW = 2 * HALF_WINDOW  # 4k ok, 6k not ok
# SLIGHTLY_LARGER_WINDOW = WINDOW + 500

#  for the 4k
HALF_WINDOW = 1000
WINDOW = 2 * HALF_WINDOW  # 4k ok, 6k not ok
SLIGHTLY_LARGER_WINDOW = WINDOW + 1000

HALF_OF_BINNING_SIZE = 500

# for the 2k
# HALF_WINDOW = 500
# WINDOW = 2 * HALF_WINDOW  # 4k ok, 6k not ok
# SLIGHTLY_LARGER_WINDOW = WINDOW + 500